defaults: &defaults
    docker: [{image: 'python:3.5'}]
    environment: {TOX_ENV: py}
    steps: &steps
        - checkout
        - run: pip install tox
        - run: tox -e $TOX_ENV
    working_directory: ~/project

defaults_cov: &defaults_cov
    <<: *defaults
    steps:
        *steps
        - run: bash <(curl -s https://codecov.io/bash)

jobs:
    test-lint: {<<: *defaults, environment: {TOX_ENV: lint}}
    test-docs: {<<: *defaults, environment: {TOX_ENV: docs}}
    test-py35: {<<: *defaults_cov}
    test-py34: {<<: *defaults_cov, docker: [{image: 'python:3.4'}]}
    test-py33: {<<: *defaults_cov, docker: [{image: 'python:3.3'}]}
    test-py27: {<<: *defaults_cov, docker: [{image: 'python:2.7'}]}
    test-pypy3: {<<: *defaults_cov, docker: [{image: 'pypy:3'}]}
    test-pypy2: {<<: *defaults_cov, docker: [{image: 'pypy:2'}]}
    deploy-pypi:
        <<: *defaults
        steps:
            - checkout
            - run: exit 1

workflows:
    tests:
        jobs: &tests
            - test-lint
            - test-docs
            - test-py35
            - test-py34
            - test-py33
            - test-py27
            - test-pypy3
            - test-pypy2
    version: 2

version: 2
