version: 2

defaults: &defaults
    environment: {TOX_ENV: py}
    steps:
        - checkout
        - run: pip install tox
        - run:
            name: "Install nose"
            command: "python -m pip install nose"
        - run:
            name: "Python version"
            command: "printf Using- && python --version"
        - run:
            name: "Nosetests"
            command: "nosetests -v"
    working_directory: ~/project

jobs:
  build-p27:
    <<: *defaults
    docker:
      - image: python:2.7
  build-p34:
    <<: *defaults
    docker:
      - image: python:3.4

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-p27:
          filters:
            branches:
              ignore: gh-pages
      - build-p34:
          filters:
            branches:
              ignore: gh-pages
