version: 2

defaults: &defaults
    environment: {TOX_ENV: py}
    steps:
        - checkout
        - run: pip install tox
        - run: tox -e $TOX_ENV
        - run: bash <(curl -s https://codecov.io/bash)
    working_directory: ~/project

jobs:
  build-p27:
    <<: *defaults
    docker:
      - image: python:2.7
  build-p34:
    <<: *defaults
    docker:
      - image: python:3.4

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-p27:
          filters:
            branches:
              ignore: gh-pages
      - build-p34:
          filters:
            branches:
              ignore: gh-pages
