version: 2

defaults: &defaults
    docker: [{image: 'python:3.5'}]
    environment: {TOX_ENV: py}
    steps:
        - checkout
        - run: pip install tox
        - run: tox -e $TOX_ENV
        - run: bash <(curl -s https://codecov.io/bash)
    working_directory: ~/project

defaults_no_cov: &defaults_no_cov
    <<: *defaults
    steps:
        - checkout
        - run: pip install tox
        - run: tox -e $TOX_ENV

jobs:
  test-lint:
    <<: *defaults_no_cov
    environment: {TOX_ENV: lint}
  test-py35:
    <<: *defaults
  test-py34:
    <<: *defaults
    docker: [{image: 'python:3.4'}]
  test-py33:
    <<: *defaults
    docker: [{image: 'python:3.3'}]

workflows:
  version: 2
  tests:
    jobs:
      - test-lint
      - test-py35
      - test-py34
      - test-py33
